### ISSUE TITLE
JSON format issue

### ISSUE THREAD

**Issue by ningli6** [ECE4574-5574/sim_harness#42]
In file LocationChangepost_ps.json, timeline_blob.json, UpdatedApp_timeblob.json, I'm pretty sure that the json blob is not correctly formatted even though it passes validations. The problem is that multiple blobs within one blob should have {} on both sides and separated by ','. Otherwise they have repeated attributes which doesn't make sense and will be combined if you run it in a web validator such as http://jsonlint.com

**Comment by aakruthigopisetty** [comment]
Yes! I agree. I will push the correct copy of those jsons in a bit. Those
were created for layout purposes.

Thanks for reminding me,

Aakruthi
